---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eklet-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - cloud.tencent.com/eklet
  labels:
{{ include "eklet.labels" . | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eklet-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - cloud.tencent.com/eklet
  labels:
{{ include "eklet.labels" . | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "nodes/status" ]
    verbs: [ "get", "list", "watch", "patch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "services", "namespaces", "secrets", "persistentvolumeclaims", "persistentvolumes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events", "configmaps", "endpoints" ]
    verbs: [ "create", "get", "list", "watch", "patch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "bindings", "pods/binding", "pods/status" ]
    verbs: [ "delete", "get", "list", "watch", "patch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts/token", "pods/eviction" ]
    verbs: [ "create" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "replicasets", "statefulsets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get","list", "watch" ]
  - apiGroups: [ "cls.cloud.tencent.com" ]
    resources: [ "logconfigs" ]
    verbs:  [ "get", "list", "watch" ]
  - apiGroups: [ "policy" ]
    resources: [ "poddisruptionbudgets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "tokenreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources: [ "localsubjectaccessreviews", "subjectaccessreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create", "get", "list", "watch", "patch", "update" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csidrivers", "csinodes" ]
    verbs: [ "create", "get", "list", "watch", "patch", "update" ]
  - apiGroups: [ "node.k8s.io" ]
    resources: [ "runtimeclasses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - update
      - create
  - apiGroups:
      - eks.tke.cloud.tencent.com
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - '*'
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eklet-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - cloud.tencent.com/eklet
  labels:
{{ include "eklet.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eklet-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: eklet-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}