---
apiVersion: v1
kind: Service
metadata:
  name: eks-eklet
  namespace: {{ .Release.Namespace }}
  finalizers:
    - cloud.tencent.com/eklet
  labels:
{{ include "eklet.labels" . | indent 4 }}
spec:
  ports:
    - port: 10241
      name: eklet
      protocol: TCP
      targetPort: 10241
  selector:
{{ include "eklet.labels" . | indent 4 }}
  type: {{ .Values.eklet.service.type }}
