apiVersion: v1
kind: Secret
metadata:
  name: eks-secret
  namespace: {{ .Release.Namespace }}
  finalizers:
    - cloud.tencent.com/eklet
  labels:
  {{ include "eks-admission.labels" . | indent 4 }}
data:
  secretID: {{ .Values.cloud.secretID | b64enc }}
  secretKey: {{ .Values.cloud.secretKey | b64enc }}